version: '3'

services: 

  twitter-app:
    build: .
    container_name: unsafe-twitter
    ports:
      - 3000:3000
    volumes: 
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    links: 
      - database
    depends_on:
      - database
    networks: 
      - app-tier

  database:
    image: mysql:5
    container_name: twitterdb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    volumes: 
      - ./data:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'twitter_db'
    networks: 
      - app-tier


networks:
  app-tier:
    driver: bridge
